package com.miaoshaProject.dataObject;

public class ItemStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.id
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.stocks
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    private Integer stocks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.item_id
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.id
     *
     * @return the value of item_stock.id
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.id
     *
     * @param id the value for item_stock.id
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.stocks
     *
     * @return the value of item_stock.stocks
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    public Integer getStocks() {
        return stocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.stocks
     *
     * @param stocks the value for item_stock.stocks
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    public void setStocks(Integer stocks) {
        this.stocks = stocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.item_id
     *
     * @return the value of item_stock.item_id
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.item_id
     *
     * @param itemId the value for item_stock.item_id
     *
     * @mbg.generated Mon Jun 29 17:38:48 EDT 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}