package com.miaoshaProject.Dao;

import com.miaoshaProject.dataObject.OrderDo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_Info
     *
     * @mbg.generated Tue Jun 30 02:57:12 EDT 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_Info
     *
     * @mbg.generated Tue Jun 30 02:57:12 EDT 2020
     */
    int insert(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_Info
     *
     * @mbg.generated Tue Jun 30 02:57:12 EDT 2020
     */
    int insertSelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_Info
     *
     * @mbg.generated Tue Jun 30 02:57:12 EDT 2020
     */
    OrderDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_Info
     *
     * @mbg.generated Tue Jun 30 02:57:12 EDT 2020
     */
    int updateByPrimaryKeySelective(OrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_Info
     *
     * @mbg.generated Tue Jun 30 02:57:12 EDT 2020
     */
    int updateByPrimaryKey(OrderDo record);
}