package com.miaoshaProject.Dao;

import com.miaoshaProject.dataObject.UserDo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbg.generated Sat Jun 27 00:30:16 EDT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbg.generated Sat Jun 27 00:30:16 EDT 2020
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbg.generated Sat Jun 27 00:30:16 EDT 2020
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbg.generated Sat Jun 27 00:30:16 EDT 2020
     */
    UserDo selectByPrimaryKey(Integer id);
    UserDo selectByTelphone(String telphone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbg.generated Sat Jun 27 00:30:16 EDT 2020
     */
    int updateByPrimaryKeySelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbg.generated Sat Jun 27 00:30:16 EDT 2020
     */
    int updateByPrimaryKey(UserDo record);
}